### ISSUE TITLE
Unable to start worker php-cgi.exe, even after in path

### ISSUE THREAD

**Issue by dylanh724** [operandom/nodejs-php-built-in-server#5]
http://i.imgur.com/yLjVv08.png
^ This screen sums it up, but pretty much,

1) I grab php5 and set env path to C:\dev\php\
2) I test by opening cmd and typing "php -v" and "php-cgi -v": Success
3) I create C:\test\ and type 'npm install sphp'
4) I browse to C:\test\node_modules\sphp\ and edit sphp.js
5) Default seems fine; i noted "php-cgi" that worked in step #2
6) I open cmd to same dir and type 'node example' >> Fail, forgot to install express etc
7) I go back twice to C:\test\ parent and type 'npm install express <etc>'
8) I go forward twice back to C:\test\node_modules\sphp and type 'node example' >> UNABLE TO START PHP-CGI.EXE 

...Why? It works in env var via normal cmd!

9) I try a direct path 'C:\dev\php\php-cgi.exe' >> Fail
10) I try a direct path 'C:/dev/php/php-cgi.exe' >> Fail
11) I tried typing #9 and 10 directly from cmd prompt and it opened php-cgi np.

12) I created test123.js and made the basic of basics script (in screenshot) >> fail (same err, of course)

What am I missing..? I'm not sure what I'm doing wrong. I'm still a node newb, so I'm hoping it's some easy step I missed..

**Comment by buddy-sandidge** [comment]
The bug and screenshot shows [`sphp`](https://github.com/paragi/sphp) being used. Is this bug for the right repo?

**Comment by operandom** [comment]
@xbudex You're right. And my repository isn't in its dependencies.

**Comment by dylanh724** [comment]
Oops ha, too many windows up at once. I couldn't get this one working either but different situation, I'll make new ticket
